export const LOGO_200x100 = {
    'AXA': 'https://www.srovnavac.cz/images/loga/200x100/axa.png',
    'AXA Assistance': 'https://www.srovnavac.cz/images/loga/200x100/axa-assist.png',
    'Slavia': 'https://www.srovnavac.cz/images/loga/200x100/slavia.png',
    'Colonnade': 'https://www.srovnavac.cz/images/loga/200x100/colonnade.png',
    'ČPP': 'https://www.srovnavac.cz/images/loga/200x100/cpp.png',
    'ČSOB Pojišťovna': 'https://www.srovnavac.cz/images/loga/200x100/csob.png',
    'ČSOB': 'https://www.srovnavac.cz/images/loga/200x100/csob.png',
    'Direct': 'https://www.srovnavac.cz/images/loga/200x100/direct.png',
    'Ergo': 'https://www.srovnavac.cz/images/loga/200x100/ergo.png',
    'Generali': 'https://www.srovnavac.cz/images/loga/200x100/generali.png',
    'Kooperativa': 'https://www.srovnavac.cz/images/loga/200x100/koop.png',
    'Allianz': 'https://www.srovnavac.cz/images/loga/200x100/allianz.png',
    'AIG': 'https://www.srovnavac.cz/images/loga/200x100/aig.png',
    'Česká pojišťovna': 'https://www.srovnavac.cz/images/loga/200x100/cp.png',
    'Uniqa': 'https://www.srovnavac.cz/images/loga/200x100/uniqa.png',
    'RB': 'https://www.srovnavac.cz/images/loga/200x100/rb.png',
    'HB': 'https://www.srovnavac.cz/images/loga/200x100/hb.png',
    'WHB': 'https://www.srovnavac.cz/images/loga/200x100/wustenrot.png',
    'Equa bank': 'https://www.srovnavac.cz/images/loga/200x100/equabank.png',
    'Mbank': 'https://www.srovnavac.cz/images/loga/200x100/mbank.png',
    'KB': 'https://www.srovnavac.cz/images/loga/200x100/kb.png',
    'MMB': 'https://www.srovnavac.cz/images/loga/200x100/moneta.png',
    'UniCredit': 'https://www.srovnavac.cz/images/loga/200x100/unicredit.png',
    'Sberbank': 'https://www.srovnavac.cz/images/loga/200x100/sberbank.png',
    'ČS': 'https://www.srovnavac.cz/images/loga/200x100/cs.png',
    'PVZP': 'https://www.srovnavac.cz/images/loga/200x100/pvzp.png',
    'Pillow': 'https://www.srovnavac.cz/images/loga/200x100/pillow.png',
    'Generali ČP': 'https://www.srovnavac.cz/images/loga/200x100/gcp.png',
    'HVP': 'https://www.srovnavac.cz/images/loga/200x100/hvp.png'
};
